## Cálculo Feedforward com Matrizes

In [84]:
import numpy as np

Estrutura de camadas da rede (3, 3, 2, 1) com bias. 
Veja figura: Fig5_RNA.tif;
Função de ativação: tanh;
Exemplo adaptado Redes Neurais Artificiais - Ivan Nunes da Silva - Cap 5.

In [85]:
#Pesos da camada 1 (oculta)
W1 = np.array([[0.2, 0.4, 0.5], [0.3, 0.6, 0.7], [0.4, 0.8, 0.3]])
W1

array([[0.2, 0.4, 0.5],
       [0.3, 0.6, 0.7],
       [0.4, 0.8, 0.3]])

In [86]:
#Pesos da camada 2 (oculta)
W2 = np.array([[-0.7, 0.6, 0.2, 0.7], [-0.3, 0.7, 0.2, 0.8]])
W2

array([[-0.7,  0.6,  0.2,  0.7],
       [-0.3,  0.7,  0.2,  0.8]])

In [87]:
#Pesos da camada 3 (saida)
W3 = np.array([0.1, 0.8, 0.5])
W3

array([0.1, 0.8, 0.5])

In [88]:
#Entradas
X = np.array([[-1, 0.3, 0.7]])
X.T

array([[-1. ],
       [ 0.3],
       [ 0.7]])

In [89]:
#Somatório dos neurônios da primeira camada
I1 = np.dot(W1, X.T)
I1

array([[0.27],
       [0.37],
       [0.05]])

In [90]:
#Saída da camada 1
Y1 = np.tanh(I1)
Y1

array([[0.26362484],
       [0.35399171],
       [0.04995837]])

In [91]:
#Adidionando a entrada de Bias da próxima camada
O1 = np.empty([len(Y1)+1, 1])  #Cria um array vazio com 1 posição a mais que Y1 em linhas e 1 coluna
O1[0] = -1                     #Coloca na primrira posição a entrada de Bias
for i in range(len(Y1)):       #Faz o append em coluna
    O1[i+1] = Y1[i]
O1



array([[-1.        ],
       [ 0.26362484],
       [ 0.35399171],
       [ 0.04995837]])

In [92]:
#Somatório dos neurônios da segunda camada
I2 = np.dot(W2, O1)
I2

array([[0.96394411],
       [0.59530243]])

In [93]:
#Saída da camada 2
Y2 = np.tanh(I2)
Y2

array([[0.74603099],
       [0.53369845]])

In [94]:
#Adidionando a entrada de Bias da próxima camada
O2 = np.empty([len(Y2)+1, 1])  #Cria um array vazio com 1 posição a mais que Y1 em linhas e 1 coluna
O2[0] = -1                     #Coloca na primrira posição a entrada de Bias
for i in range(len(Y2)):       #Faz o append em coluna
    O2[i+1] = Y2[i]
O2

array([[-1.        ],
       [ 0.74603099],
       [ 0.53369845]])

In [96]:
#Somatório dos neurônios da terceira camada (saída)
I3 = np.dot(W3, O2)
I3

array([0.76367401])

In [97]:
#Saída da camada 3 (saída da rede)
Y3 = np.tanh(I3)
Y3

array([0.64323593])